#Default config file

#Height above ground to drop player back into the world at
#when they have been teleported
drop-height: 20

#Distance player will fall through the void before being teleported
fall-distance: 50

#What permissions systems to use
permissions:

    #Allow ops to execute all commands
    op: true
    
    #Use permission nodes (inactive)
    nodes:
        
        #Enable/diable the admin permission node
        admin: true
        
        #User's require node to be teleported
        user: true
        
        #Enable the node that allows players to be exempt from teleport costs
        free: true
        
    #Do use a Super Permissions compatible manager?
    bukkit: true
      
    #Do you use vault? (Not needed if you use a SuperPerms compatible manager)
    vault: false
    
economy:
    #Enable to enable/diable warp costs
    enable: false
    
    #Enable to use vault to manage ecomonomy
    vault: true

#Warp destination
destination:

    #World to teleport player to
    world: world
    
    #x co-ordinate in specified world
    x: 0
    
    #No y co-ordinate as you always appear at the highest point.
    #Wouldn't be like you fell from the sky if you didn't.
    
    #x co-ordinate in specified world
    z: 0
   
#Enable the plugin 
enable: true