name: VoidWarp
main: me.flungo.bukkit.VoidWarp.VoidWarp
version: 0.4.2
description: >
              Teleports you to the spawn of a specified world when you fall through the void.
commands:
    vwenable:
        description: Enables the plugin.
        usage: /vwenable
    vwdisable:
        description: Disables the plugin.
        usage: /vwdisable
    vwset:
        description: Sets warp point to current location.
        usage: /vwset
permissions:
    voidwarp.admin:
        description: Allows use of all commands.
        children:
            voidwarp.user: true
    voidwarp.user:
    	description: Allows user to fall through voids and be warped without dying.